## ARRAY OPERATIONS
1. Arithmetic operations
2. Broadcasting
3. Deep and Shallow copy
4. Matrix operations


In [1]:
import numpy as np
# Array operations
ar1=np.arange(1,6)
ar2=np.arange(6,11)
print(ar1)
print(ar2)
print("Addition: ",ar1+ar2)
print("Substraction: ",ar1-ar2)
print("Divition: ",ar1/ar2)
print("Floor Division: ",ar1//ar2)
print("Multiplication: ",ar1*ar2)
print("Power:  ",ar1**ar2)
print("All the arithmettic operations are completed and there should bew equal no of elemnts in both the elemnts or else there will be broadcasting error we will see more in pandas")

[1 2 3 4 5]
[ 6  7  8  9 10]
Addition:  [ 7  9 11 13 15]
Substraction:  [-5 -5 -5 -5 -5]
Divition:  [0.16666667 0.28571429 0.375      0.44444444 0.5       ]
Floor Division:  [0 0 0 0 0]
Multiplication:  [ 6 14 24 36 50]
Power:   [      1     128    6561  262144 9765625]
All the arithmettic operations are completed and there should bew equal no of elemnts in both the elemnts or else there will be broadcasting error we will see more in pandas


In [5]:
#broadcasting
#broadcasting is use when u wanbt to add single elemt or something to rest of the multiple data in the array
import numpy as np
arr= np.array([10,20,30,40]) 
print(arr*41)
print(arr+10)
print(arr//10)


[ 410  820 1230 1640]
[20 30 40 50]
[1 2 3 4]


In [7]:
#deep and shallow copy
arr=np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [11]:
a=arr[0:9]
a=a*10
print(a)

[10 20 30 40 50 60 70 80 90]


In [ ]:
b=a
b[0]=100 #deepcopy
a

array([100,  20,  30,  40,  50,  60,  70,  80,  90])

In [23]:
#shallow copy
c=a.copy()

c[3]=100
print(c)
print(a)

[100  20  30 100  50  60  70  80  90]
[100  20  30  40  50  60  70  80  90]


In [12]:
#Matrixoperations
mat1=np.array([[1,2],[3,4]])
mat2=np.array([[5,6],[7,8]])
mat1

array([[1, 2],
       [3, 4]])

In [13]:
mat2

array([[5, 6],
       [7, 8]])

In [16]:
print(mat1 @ mat2 )#matrix multiplication
print(mat1-mat2)

[[19 22]
 [43 50]]
[[-4 -4]
 [-4 -4]]


In [28]:
#transpose is 
mat1.T

array([[1, 3],
       [2, 4]])

## Advance array Manipulation
1. Stacking array
2. splitting array 

In [41]:
a1=np.array([1,2,3,4])
b1=np.array([5,6,7,8])
a1
b1

array([5, 6, 7, 8])

In [42]:
np.vstack((a1,b1))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [43]:
np.hstack((a1,b1))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [44]:
np.column_stack((a1,b1))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [17]:
j=np.arange(1,31).reshape(5,6)
print(j)
#plitting


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]


In [18]:
k=np.vsplit(j,5)
k

[array([[1, 2, 3, 4, 5, 6]]),
 array([[ 7,  8,  9, 10, 11, 12]]),
 array([[13, 14, 15, 16, 17, 18]]),
 array([[19, 20, 21, 22, 23, 24]]),
 array([[25, 26, 27, 28, 29, 30]])]

In [60]:
l=np.hsplit(j,3)
print(l)

[array([[ 1,  2],
       [ 7,  8],
       [13, 14],
       [19, 20],
       [25, 26]]), array([[ 3,  4],
       [ 9, 10],
       [15, 16],
       [21, 22],
       [27, 28]]), array([[ 5,  6],
       [11, 12],
       [17, 18],
       [23, 24],
       [29, 30]])]
