In [2]:
import numpy as np
arr=np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [4]:
print(arr[2])

3


In [5]:
print(arr[1:6])

[2 3 4 5 6]


##  Array indexing and slicing 


In [7]:
arr=np.arange(1,31).reshape(6,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [9]:
print(arr[0:2,1:3])

[[2 3]
 [7 8]]


In [11]:
print(arr[3: ,2: ])

[[18 19 20]
 [23 24 25]
 [28 29 30]]


## BOOLEAN INDEXING


In [13]:
arr1= np.arange(1,31)
print(arr1)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]


In [18]:
bool_ind=arr%2==0
print(bool_ind)

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True]


In [19]:
arr=arr[bool_ind]
print(arr)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]


In [6]:
import numpy as np
arr=np.random.randint(10,20,10)
print(arr)

[14 14 17 18 18 12 16 14 14 15]


In [22]:
print(np.random.randn(10))

[-1.53975296  0.24570591  0.2916846   0.32663653  0.75273454 -1.8048728
 -0.41248672  0.49565447 -0.07169856 -1.16706563]


In [33]:
arr=np.arange(100).reshape(10,10)
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.argmax())
print(arr.argmin())
print(arr.mean())
print(arr.sum())
print(arr[1:9,2:])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
2
(10, 10)
99
0
49.5
4950
[[12 13 14 15 16 17 18 19]
 [22 23 24 25 26 27 28 29]
 [32 33 34 35 36 37 38 39]
 [42 43 44 45 46 47 48 49]
 [52 53 54 55 56 57 58 59]
 [62 63 64 65 66 67 68 69]
 [72 73 74 75 76 77 78 79]
 [82 83 84 85 86 87 88 89]]
