In [4]:
import numpy as np

# 1. Create a 1D array from a Python list
arr = np.array([1, 2, 3, 4, 5])
print("Original Array:", arr)

# 2. Perform a fast element-wise operation (multiply every item by 2)
doubled_arr = arr * 2
print("Doubled Array: ", doubled_arr)

# 3. Calculate the sum of all elements
total_sum = np.sum(arr)
print("Sum of elements:", total_sum)


Original Array: [1 2 3 4 5]
Doubled Array:  [ 2  4  6  8 10]
Sum of elements: 15


In [5]:
import sys
print(sys.version)


3.13.5 | packaged by Anaconda, Inc. | (main, Jun 12 2025, 16:37:03) [MSC v.1929 64 bit (AMD64)]


In [6]:
import numpy as np
arr=np.array([1,3,5,8,10])
arr
print(arr)

[ 1  3  5  8 10]


In [7]:
import numpy as np
arr=[[1,2,3],[4,5,6],[7,8,9]]
np.array(arr)



array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
ar=np.arange(1,100,9)
ar

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [9]:
arr=np.linspace(1,100,50)
print(arr)

[  1.           3.02040816   5.04081633   7.06122449   9.08163265
  11.10204082  13.12244898  15.14285714  17.16326531  19.18367347
  21.20408163  23.2244898   25.24489796  27.26530612  29.28571429
  31.30612245  33.32653061  35.34693878  37.36734694  39.3877551
  41.40816327  43.42857143  45.44897959  47.46938776  49.48979592
  51.51020408  53.53061224  55.55102041  57.57142857  59.59183673
  61.6122449   63.63265306  65.65306122  67.67346939  69.69387755
  71.71428571  73.73469388  75.75510204  77.7755102   79.79591837
  81.81632653  83.83673469  85.85714286  87.87755102  89.89795918
  91.91836735  93.93877551  95.95918367  97.97959184 100.        ]


## we are doing random generation function

In [10]:
np.random.rand(6)

array([0.70499669, 0.8658423 , 0.09655792, 0.06241896, 0.1677948 ,
       0.44964389])

In [11]:
np.random.randn(10)

array([ 0.39949873, -0.32280665,  0.19531061, -0.2982908 ,  0.73972858,
        0.10894218, -0.29817134, -0.35985121,  0.01665906,  1.18152779])

In [12]:
np.random.randint(10,20,10)

array([10, 10, 16, 18, 14, 13, 16, 12, 16, 15], dtype=int32)

##Array attribute

In [13]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
arr.size


9

In [15]:
arr.shape

(3, 3)

In [16]:
arr.dtype

dtype('int64')

##Array methods

In [17]:
print(arr.max())

9


In [18]:
print(arr.min())

1


In [19]:
print(arr.sum())

45


In [20]:
print(np.sum(arr,axis=1))
print(np.sum(arr,axis=0))

[ 6 15 24]
[12 15 18]


In [21]:
print(arr.mean())

5.0


In [22]:
print(arr.std())

2.581988897471611


In [23]:
print(arr.var())

6.666666666666667


In [24]:
arr=np.arange(1,34)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33])

In [25]:
arr.reshape(11,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30],
       [31, 32, 33]])

In [26]:
#create a numpy array of 4x4 with values 1 to 16 replace disgonal with 0
import numpy as np
arr=np.arange(16).reshape(4,4)
print(arr)
np.fill_diagonal(arr,0)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3]
 [ 4  0  6  7]
 [ 8  9  0 11]
 [12 13 14  0]]


In [27]:
#create a numpyy array of 6x6 for 36 and themn extract the subarray consisting of the 3rd to 5th rows and 2nd to 4th columns
arr2=np.arange(36).reshape(6,6)
print("the array is: ",arr2)
print("Subarray of the 3rd to 5th row and 2nd to 4th columns \n::", arr2[3: ,2: 5])

the array is:  [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
Subarray of the 3rd to 5th row and 2nd to 4th columns 
:: [[20 21 22]
 [26 27 28]
 [32 33 34]]


In [28]:
import numpy as np
arr=np.arange(16).reshape(4,4)
print(arr)
s1=np.sum(arr,axis=1)
s2=np.sum(arr,axis=0)
print("sum array : ",s1)
print("sum colum : ",s2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
sum array :  [ 6 22 38 54]
sum colum :  [24 28 32 36]


In [29]:
mat1= np.random.randint(1,31,size=(3,3))
mat2= np.random.randint(1,31,size=(3,3))
mat3=mat1*mat2
print(mat3)
mat4=mat1+mat2
print(mat4)

[[150 644 160]
 [360 312  28]
 [100 200  54]]
[[31 51 28]
 [42 38 11]
 [20 30 29]]


In [30]:
arr=np.random.randint(1,101,(5,5))
print(arr)

print("top", arr[0 ,:])
print("right column",arr[:,4])
print("bottom", arr[4,:])
print("left column",arr[:,0])

[[65 64 45 48 98]
 [56 45 82  5 74]
 [38 95 24 76 54]
 [39 57  1 24 28]
 [ 1 35 93 17 40]]
top [65 64 45 48 98]
right column [98 74 54 28 40]
bottom [ 1 35 93 17 40]
left column [65 56 38 39  1]


In [31]:
#reverse a numpy array
num=np.arange(1,10)
print(num)
num=num[::-1]
print(num)


[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]


In [32]:
boole=np.random.randint(5,20,(4,4))
print(boole)
boole[boole>10]=10
print(boole)

[[11 10 11  7]
 [14 16 15  7]
 [ 9 16 10  6]
 [17  9  5 14]]
[[10 10 10  7]
 [10 10 10  7]
 [ 9 10 10  6]
 [10  9  5 10]]


In [33]:
# 13. Create a one-dimensional NumPy array using the arange() function, with elements ranging from 10 to 30, incremented by 4 (i.e., include both 10 and 30). Reshape this array into a 2D array of shape (2, 3). Then, display only those elements of this 2D array that are divisible by 5. 
arr=np.arange(10,31,4).reshape(2,3)
print(arr)
Ae=arr[arr%5==0]
print(Ae)

[[10 14 18]
 [22 26 30]]
[10 30]


In [38]:
# 14. Create a 2-D array called myarray4 using arange() having 14 rows and 3 columns with start value = -1, step size 0.25 having. Split this array row-wise into 3 equal parts and print the result. 
import numpy as np
myarray4=np.arange(-1,9.5,0.25).reshape(14,3)
print(myarray4)


[[-1.   -0.75 -0.5 ]
 [-0.25  0.    0.25]
 [ 0.5   0.75  1.  ]
 [ 1.25  1.5   1.75]
 [ 2.    2.25  2.5 ]
 [ 2.75  3.    3.25]
 [ 3.5   3.75  4.  ]
 [ 4.25  4.5   4.75]
 [ 5.    5.25  5.5 ]
 [ 5.75  6.    6.25]
 [ 6.5   6.75  7.  ]
 [ 7.25  7.5   7.75]
 [ 8.    8.25  8.5 ]
 [ 8.75  9.    9.25]]


In [45]:
# A fitness tracker records the number of steps taken each hour for a full day (24 readings). Due to a device error, a few values were recorded as negatives or abnormally high. You are provided a 1-D array of 24 values. Analyze this data and determine how active the user was during the day. Verify if any suspicious readings require correction. Identify periods of high and low activity. 

steps=np.array([5000,2000,-100,78920,6541,9000,100000,8779,21003,5645,8974,4561,-2000,4567,12300,89456,132456,9874,21000,55660,65477,2000,8900])
print(steps)
# ------------------------------------------------
# 1. Identify negative values
# ------------------------------------------------
negative_indices = np.where(steps < 0)[0]
print("\nNegative readings:")
for i in negative_indices:
    print(f"Hour {i + 1}: {steps[i]}")
# ------------------------------------------------
# 2. Detect abnormally high values
# ------------------------------------------------
valid_data = steps[steps >= 0]
mean = np.mean(valid_data)
std = np.std(valid_data)
upper_limit = mean + 2 * std
high_indices = np.where(steps > upper_limit)[0]
print("\nSuspiciously high readings:")
for i in high_indices:
    print(f"Hour {i + 1}: {steps[i]}")
print("\nUpper limit:", upper_limit)
# ------------------------------------------------
# 3. Correct suspicious values
# ------------------------------------------------
suspicious_indices = np.unique(
    np.concatenate((negative_indices, high_indices))
)
median = np.median(valid_data)
corrected_steps = steps.copy()
for i in suspicious_indices:
    corrected_steps[i] = median

print("\nCorrected data:")
print(corrected_steps)
# ------------------------------------------------
# 4. Overall activity
# ------------------------------------------------
total_steps = np.sum(corrected_steps)
average_steps = np.mean(corrected_steps)

print("\nTotal steps:", total_steps)
print("Average steps/hour:", average_steps)
# ------------------------------------------------
# 5. High and low activity periods
# ------------------------------------------------
activity_median = np.median(corrected_steps)

high_activity = np.where(corrected_steps > activity_median)[0]
low_activity = np.where(corrected_steps < activity_median)[0]

print("\nHigh activity hours:")
print(high_activity + 1)

print("\nLow activity hours:")
print(low_activity + 1)
# ------------------------------------------------
# 6. Most and least active hour
# ------------------------------------------------
most_active = np.argmax(corrected_steps)
least_active = np.argmin(corrected_steps)
print("\nMost active:")
print(f"Hour {most_active + 1}: {corrected_steps[most_active]} steps")
print("\nLeast active:")
print(f"Hour {least_active + 1}: {corrected_steps[least_active]} steps")

[  5000   2000   -100  78920   6541   9000 100000   8779  21003   5645
   8974   4561  -2000   4567  12300  89456 132456   9874  21000  55660
  65477   2000   8900]

Negative readings:
Hour 3: -100
Hour 13: -2000

Suspiciously high readings:
Hour 17: 132456

Upper limit: 107283.95075711265

Corrected data:
[  5000   2000   9000  78920   6541   9000 100000   8779  21003   5645
   8974   4561   9000   4567  12300  89456   9000   9874  21000  55660
  65477   2000   8900]

Total steps: 546657
Average steps/hour: 23767.695652173912

High activity hours:
[ 4  7  9 15 16 18 19 20 21]

Low activity hours:
[ 1  2  5  8 10 11 12 14 22 23]

Most active:
Hour 7: 100000 steps

Least active:
Hour 2: 2000 steps


In [59]:
#16. You’re given the test scores (out of 100) of 40 students as a 1-D array. However, some students were absent, marked as -1. The instructor wants to calculate valid statistics, excluding students who are absent. Grades must be assigned based on the distribution of performance. Can you clean the data, summarize the performance, and suggest how grading can be done? 
import numpy as np

# Test scores of 40 students
scores = np.array([
    85, 72, -1, 91, 66, 78, 54, 88, -1, 95,
    43, 61, 74, 82, 69, -1, 57, 90, 76, 84,
    38, 71, 63, 97, -1, 52, 80, 68, 59, 87,
    73, 45, 92, -1, 64, 79, 86, 55, 70, 94
])
#identify absent students
absent= scores==-1
print(np.sum(absent))
#remove absent students
valid=scores[scores!=-1]
print(valid)
#3. Calculate statistics
mean1=np.mean(valid)
std_dev=np.std(valid)
meadian=np.median(valid)
max=np.max(valid)
min=np.min(valid)
print("Average of the corrected marks: ", mean1)
print("The std dev of the marks: ", std_dev)
print("meadian of the scores:",meadian)
print("the max and min scores are :", max,min)
#assign grades
grades = np.empty(len(scores), dtype="<U2")
# Mark absent students
grades[scores == -1] = "NA"
grades[(scores >= 90)] = "A"
grades[(scores >= 75) & (scores < 90)] = "B"
grades[(scores >= 60) & (scores < 75)] = "C"
grades[(scores >= 40) & (scores < 60)] = "D"
grades[(scores >= 0) & (scores < 40)] = "F"

print("\nGrades:")
print(grades)

#count grades 
for grade in ["A","B","C","D","F"]:
    count =np.sum(grades==grade)
    print(grade," : ",count) 

5
[85 72 91 66 78 54 88 95 43 61 74 82 69 57 90 76 84 38 71 63 97 52 80 68
 59 87 73 45 92 64 79 86 55 70 94]
Average of the corrected marks:  72.51428571428572
The std dev of the marks:  15.527618580307484
meadian of the scores: 73.0
the max and min scores are : 97 38

Grades:
['B' 'C' 'NA' 'A' 'C' 'B' 'D' 'B' 'NA' 'A' 'D' 'C' 'C' 'B' 'C' 'NA' 'D'
 'A' 'B' 'B' 'F' 'C' 'C' 'A' 'NA' 'D' 'B' 'C' 'D' 'B' 'C' 'D' 'A' 'NA' 'C'
 'B' 'B' 'D' 'C' 'A']
A  :  6
B  :  10
C  :  11
D  :  7
F  :  1


In [69]:
temps = np.array([
    [25, 27, 29, 31, 30, 28, 26, 24],
    [24, 26, 28, 30, 32, 29, 27, 25],
    [23, 25, 27, 29, 31, 30, 26, 24],
    [26, 28, 30, 33, 35, 32, 29, 27],
    [22, 24, 25, 27, 28, 26, 23, 21],
    [25, 27, 29, 31, 100, 30, 27, 24],
    [24, 26, 28, 30, 31, 29, 26, 23]
])

# Overall average temperature
print("Average temperature:", np.mean(temps))

# Shape
print("Shape of array:", np.shape(temps))

# Average temperature of each day
daily_average = np.mean(temps, axis=1)

print("\nDaily averages:")
print(daily_average)

# Hottest day
hottest_day = np.argmax(daily_average) + 1

# Coldest day
coldest_day = np.argmin(daily_average) + 1

print("\nHottest day:", hottest_day)
print("Coldest day:", coldest_day)

# Sensor error detection
average = np.mean(temps)
standard_deviation = np.std(temps)

upper_limit = average + 2 * standard_deviation
lower_limit = average - 2 * standard_deviation

Error = (temps > upper_limit) | (temps < lower_limit)

print("\nSuspicious readings:")
print(temps[Error])
day, hour = np.where(Error)
for d, h in zip(day, hour):
    print(
        "Day:", d + 1,
        "Reading:", h + 1,
        "Temperature:", temps[d, h]
    )
    

Average temperature: 28.607142857142858
Shape of array: (7, 8)

Daily averages:
[27.5   27.625 26.875 30.    24.5   36.625 27.125]

Hottest day: 6
Coldest day: 5

Suspicious readings:
[100]
Day: 6 Reading: 5 Temperature: 100


In [79]:
#19. You are given a matrix of electricity usage (in units) for 5 households over 6 months. Compute the total bill for each household, assuming tiered pricing: a. First 100 units → ₹5/unit b. Next 100 → ₹8/unit c. Remaining → ₹10/unit Also, identify which household had the most consistent usage and which month had the highest average usage. 

usage = np.array([
    [80, 120, 150, 90, 110, 130],
    [200, 220, 180, 250, 210, 230],
    [50, 70, 60, 80, 55, 65],
    [150, 140, 160, 155, 145, 150],
    [300, 280, 320, 310, 290, 330]
])
#total usage of the each household 
total_usage=np.sum(usage,axis=1)
print("The total usage of the each house hold is :: \n",total_usage)

def total_cost_of_unit(units):
    if(units<=100):
        return units*5
    elif(units <=200):
        return 100*5+((units-100)*8)
    else:
        return 100*5+100*8+((units-200)*10)
i=1
for unit in total_usage:
    print(f"The bill house {i} needs to pay is {total_cost_of_unit(unit)}")
    i+=1
print(f"The dimention and shape of the matrix is {np.ndim(usage)} and {np.shape(usage)}")

#Most consistent 
Consistency=np.std(usage,axis=1)
print(f"The household that is most consistence is {np.argmin(Consistency)+1} ")

#Month with highest average usgae 
Highest=np.mean(usage,axis=0)
print(Highest)
print(f"The month with highest average usage is : {np.argmax(Highest)+1}")

The total usage of the each house hold is :: 
 [ 680 1290  380  900 1830]
The bill house 1 needs to pay is 6100
The bill house 2 needs to pay is 12200
The bill house 3 needs to pay is 3100
The bill house 4 needs to pay is 8300
The bill house 5 needs to pay is 17600
The dimention and shape of the matrix is 2 and (5, 6)
The household that is most consistence is 4 
[156. 166. 174. 177. 162. 181.]
The month with highest average usage is : 6


In [92]:
#A digital vault is protected by a 3×3 key matrix K. To unlock the vault, the control system performs the following: It transposes the matrix K and multiplies it with the original matrix K. Then, it computes the trace of the resulting matrix. Finally, it takes the square root of that trace and rounds it to the nearest integer to get the unlock code. 
import numpy as np

k = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Original matrix:")
print(k)

# Transpose
k_T = k.T

print("\nTranspose:")
print(k_T)

# Transpose × Original
mul = np.matmul(k_T, k)

print("\nK^T * K:")
print(mul)

# Trace
trace = np.trace(mul)

print("\nTrace:", trace)

# Square root and round
unlock = np.around(np.sqrt(trace))

print("Unlock code:", unlock)


Original matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Transpose:
[[1 4 7]
 [2 5 8]
 [3 6 9]]

K^T * K:
[[ 66  78  90]
 [ 78  93 108]
 [ 90 108 126]]

Trace: 285
Unlock code: 17.0
